name: agrarian-app-ci-workflow
on: 
  push:
    branches:
    - 'agrarian_docker_build'
    - '!test'
    - '!master'
    paths:
    - 'App/Build/**'
    - '.github/workflows/**'
    - '!README.md'
jobs:
  agrarian-test:
    name: agrarian-test-suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose -f App/Build/docker-compose.yaml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Testing node-red-backend
      run: docker run --network build_node-red-net appropriate/curl -s --retry 10 --retry-connrefused http://localhost:1880/ 
    - name: Testing mqtt-broker
      run: nc -q 2 localhost 1883
    - name: Testing mongo-db
      run: nc -q 2 localhost 27017

  deploy:
    name: Deploy webhook call
    runs-on: ubuntu-latest
    needs: [agrarian-test]
    steps:
    - name: Deploy agrarian docker-compose
      uses: joelwmale/webhook-action@master
    with:
      url: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
      headers: '{"repository": "ertush/agrarian"}'
      body: '{"git_secret": ${{ secrets.GIT_SECRET }}}'