name: agrarian-app-ci-workflow
on: 
  push:
    branches:
    - 'agrarian_docker_build'
    - '!test'
    - '!master'
    paths:
    - 'App/Build/**'
    - '.github/workflows/**'
    - '!README.md'
jobs:
  agrarian-test:
    name: agrarian-test-suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose -f App/Build/docker-compose.yaml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Testing node-red-backend
      run: curl -Is http://localhost:1880 | head -n 1 
    - name: Testing mqtt-broker
      run: docker exec -d mqtt-broker nc -q 2 localhost 1883
    - name: Testing influx-db
      run: docker exec -d influx-db nc -q 2 localhost 8086

  deploy:
    name: Deploy webhook call
    runs-on: ubuntu-latest
    needs: [agrarian-test]
    steps:
    - name: Deploy agrarian docker-compose
      env:
        SECRET: ${{ secrets.GIT_SECRET }}
        DB_USER: ${{ secrets.INFLUXDB_USER_PASSWORD }}
        DB_ADMIN: ${{ secrets.INFLUXDB_ADMIN_PASSWORD }}
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
        headers: '{"Content-Type": "application/json"}'
        body: '{"secret": "$SECRET", "db_user": "$DB_USER", "db_admin": "$DB_ADMIN"}'